import type { Astrologer } from '@/types';

export const mockAstrologers: Astrologer[] = [
  {
    id: 1,
    name: 'Bhavisha Barot',
    photo_url: null,
    specializations: ['Vedic'],
    experience_years: 3,
    languages: ['Hindi', 'Gujarati'],
    total_orders: 574,
    total_chats: 1200,
    rating: 4.8,
    price_per_min: 10,
    price_per_chat: null,
    discount_percent: 0,
    is_ai: false,
    is_verified: true,
    is_available: true,
    bio: 'Experienced Vedic astrologer specializing in relationship and career guidance.',
    created_at: '',
  },
  {
    id: 2,
    name: 'AI Riya',
    photo_url: null,
    specializations: ['Vedic', 'AI Astrology'],
    experience_years: null,
    languages: ['Hindi', 'English'],
    total_orders: 0,
    total_chats: 25600,
    rating: 4.9,
    price_per_min: null,
    price_per_chat: 50,
    discount_percent: 100,
    is_ai: true,
    is_verified: true,
    is_available: true,
    bio: 'AI-powered astrologer providing instant, personalized Vedic astrology insights 24/7.',
    created_at: '',
  },
  {
    id: 3,
    name: 'Ashok Shukla',
    photo_url: null,
    specializations: ['Vedic', 'Prashna'],
    experience_years: 28,
    languages: ['Hindi'],
    total_orders: 463,
    total_chats: 890,
    rating: 4.7,
    price_per_min: 31,
    price_per_chat: null,
    discount_percent: 59,
    is_ai: false,
    is_verified: true,
    is_available: true,
    bio: 'Senior Vedic and Prashna astrologer with 28 years of experience.',
    created_at: '',
  },
  {
    id: 4,
    name: 'Divyakant Akruvala',
    photo_url: null,
    specializations: ['Vedic'],
    experience_years: 20,
    languages: ['Hindi', 'English'],
    total_orders: 309,
    total_chats: 650,
    rating: 4.6,
    price_per_min: 36,
    price_per_chat: null,
    discount_percent: 10,
    is_ai: false,
    is_verified: true,
    is_available: false,
    bio: 'Dedicated Vedic astrologer with 20 years of experience.',
    created_at: '',
  },
  {
    id: 5,
    name: 'AI Kiran',
    photo_url: null,
    specializations: ['Vedic', 'Numerology', 'AI Astrology'],
    experience_years: null,
    languages: ['Hindi', 'English', 'Tamil'],
    total_orders: 0,
    total_chats: 18200,
    rating: 4.8,
    price_per_min: null,
    price_per_chat: 50,
    discount_percent: 100,
    is_ai: true,
    is_verified: true,
    is_available: true,
    bio: 'Analytical AI astrologer combining Vedic wisdom with numerology.',
    created_at: '',
  },
];

export const exploreFeatures = [
  {
    title: 'CHAT',
    subtitle: 'Chat and Get Answers',
    badge: 'FREE AI CHAT',
    href: '/chat',
    gradient: 'from-primary to-indigo-600',
    iconBg: 'bg-white/20',
    icon: (
      <svg className="w-7 h-7 text-white" viewBox="0 0 24 24" fill="currentColor">
        <path d="M21 15a2 2 0 01-2 2H7l-4 4V5a2 2 0 012-2h14a2 2 0 012 2v10z" />
      </svg>
    ),
    comingSoon: false,
  },
  {
    title: 'PANCHANG',
    subtitle: "Today's Good Time",
    badge: 'KRISHNA PRATIPADA',
    href: '/panchang',
    gradient: 'from-accent-dark to-amber-600',
    iconBg: 'bg-orange-300/25',
    icon: (
      <span className="text-2xl">📅</span>
    ),
    comingSoon: false,
  },
  {
    title: 'COMPATIBILITY',
    subtitle: 'Check Your Match',
    badge: 'GUN MILAN',
    href: '/compatibility',
    gradient: 'from-pink-600 to-rose-500',
    iconBg: 'bg-pink-300/25',
    icon: (
      <span className="text-2xl">❤️</span>
    ),
    comingSoon: false,
  },
  {
    title: 'KUNDLI',
    subtitle: 'Birth Chart Insights',
    badge: 'BIRTH CHART',
    href: '/kundli',
    gradient: 'from-indigo-600 to-blue-600',
    iconBg: 'bg-blue-300/25',
    icon: (
      <span className="text-2xl">🔯</span>
    ),
    comingSoon: false,
  },
  {
    title: 'CALCULATORS',
    subtitle: 'Vedic Calculators',
    badge: 'NEW',
    href: '/calculators',
    gradient: 'from-cyan-600 to-teal-600',
    iconBg: 'bg-cyan-300/25',
    icon: (
      <span className="text-2xl">🧮</span>
    ),
    comingSoon: false,
  },
  {
    title: 'MUHURAT',
    subtitle: 'Auspicious Times',
    badge: 'SHUBH MUHURAT',
    href: '/muhurat',
    gradient: 'from-orange-600 to-amber-500',
    iconBg: 'bg-yellow-300/25',
    icon: (
      <span className="text-2xl">🕉️</span>
    ),
    comingSoon: false,
  },
  {
    title: 'CALENDAR',
    subtitle: 'Festivals & Panchang',
    badge: 'HINDU CALENDAR',
    href: '/calendar',
    gradient: 'from-amber-500 to-yellow-500',
    iconBg: 'bg-amber-300/25',
    icon: (
      <span className="text-2xl">🪔</span>
    ),
    comingSoon: false,
  },
];
