export function StatusSection() {
  return (
    <section className="px-4 pb-16 pt-8 sm:px-6 sm:pb-20 sm:pt-12 lg:px-8">
      <div className="mx-auto max-w-[1000px]">
        <div className="relative overflow-hidden rounded-[20px] border border-white/[0.15] bg-gradient-to-br from-elevated to-surface p-6 sm:p-10">
          {/* Top gradient line */}
          <div
            className="absolute left-0 right-0 top-0 h-[3px]"
            style={{
              background: "linear-gradient(90deg, var(--gold), var(--saturn), var(--mars), var(--gold))",
            }}
          />

          <div className="status-badge mb-5 inline-flex items-center gap-2 rounded-full border border-gold/30 bg-gold-dim px-4 py-2 text-xs font-semibold uppercase tracking-widest text-gold-bright">
            <span className="h-1.5 w-1.5 animate-pulse rounded-full bg-gold" />
            Live Cosmic Update
          </div>

          <h2 className="mb-3 font-display text-2xl font-normal leading-tight text-[#f0ebe3] sm:text-3xl md:text-4xl">
            Saturn Enters Aries — A 29-Year Cycle Begins
          </h2>

          <p className="max-w-[700px] text-sm leading-relaxed text-white/70 sm:text-base">
            After nearly three decades, Saturn transits into Aries, initiating a powerful karmic cycle. This celestial shift brings transformation to leadership, ambition, and collective action. Industries facing restructuring: defense, technology, and governance.
          </p>

          <div className="mt-6 flex flex-wrap gap-4 border-t border-white/[0.08] pt-6 text-xs text-white/45 sm:gap-8 sm:text-sm">
            <span>☿ Generated by Daivik Prediction Engine</span>
            <span>◷ Updated 2 hours ago</span>
          </div>
        </div>
      </div>
    </section>
  );
}
